name: Lint

on: [push]

jobs:
  clang-tidy:
    name: clang-tidy
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Manually install clang-tools v16
      run: |
        wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
        sudo add-apt-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-16 main"
        sudo apt install clang-tools-16 clang-tidy-16 clang-format-16

    - name: Run clang-tidy on all files
      uses: cpp-linter/cpp-linter-action@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        style: ''
        tidy-checks: ''
        version: 16
        files-changed-only: false

